### ISSUE TITLE
Update definition

### ISSUE THREAD

**Issue by stevehipwell** [fabmation-gmbh/helm-whatup#36]
Could you please confirm for me which version is being used when looking at updates and how they results are sorted?

As a starting offer I would expect an update to be defined as an update to the current chart or a newer application version available in another chart. This would be correct in my opinion as the chart version only has a relationship to itself, while the app version is the primary data point (without a qualitive assessment of the chart code). This could be combined with a flag to show all different options as are currently displayed.

FYI I really appreciate that you've kept this plugin working as I feel an outdated command should be part of core Helm (it's a fundamental package manager feature).

**Comment by l0nax** [comment]
The `Installed Version` and `Latest Version` do hold the _Chart version_.
The sorting is done by _helm_ itself, and _helm_ does sort by the release name.

Would it help you if we change `Installed Version` to `Installed Chart Version`?

**Comment by stevehipwell** [comment]
I think that fundamentally the app version is the important data point here, chart version is only informative where the user understands the context of the chart.

**Comment by stevehipwell** [comment]
For example take the following real output.

```
NAME                    fluent-bit
NAMESPACE               logging
INSTALLED VERSION       0.8.2

REPOSITORY      DEPRECATED      CHART VERSION   APP VERSION     UPDATED
aws             false           0.1.6           2.7.0           2021-01-26 23:03:14.0644869 +0000 UTC
fluent          false           0.9.0           1.6.10          2021-01-26 14:26:57.006863217 +0000 UTC
grafana         false           2.2.0           v2.1.0          2020-12-24 15:07:11.404389629 +0000 UTC
stable          true            2.10.3          1.3.7           2020-11-14 13:06:25.577818 +0000 UTC
```
I **know** that the correct answer to which update is needed is the `fluent` chart (it's the official chart and the latest _fluent-bit_ version is _v1.6.10_) is but the numbers might suggest otherwise. The only automated logic that would apply here is that it's the currently installed chart (https://github.com/fabmation-gmbh/helm-whatup/issues/37); everything else is context.

MVP improvements would be the current app version being displayed in the top group and deprecated charts being ignored (https://github.com/fabmation-gmbh/helm-whatup/issues/35). Further improvements could  be to only show other charts when the current chart(s) is/are deprecated unless a flag is provided; in the above example I'm not interested in anything other than the `fluent` repo for `fluent-bit` and would prefer the single line view if possible.

**Comment by l0nax** [comment]
> I know that the correct answer to which update is needed is the fluent chat […]

I added `INSTALLED APP VERSION` to the top group (implemented in 65955ee2c8a553801f93f7350a8678b1095a0dc6):
```
NAME                       postgresql
NAMESPACE                  devops
INSTALLED CHART VERSION    6.2.1
INSTALLED APP VERSION      11.7.0

REPOSITORY	DEPRECATED	CHART VERSION	APP VERSION	UPDATED                                
stable    	true      	8.6.4        	11.7.0     	2020-10-15 19:46:22.568144 +0000 UTC   
bitnami   	false     	10.2.5       	11.10.0    	2021-01-25 11:45:54.496172456 +0000 UTC
```

**Comment by l0nax** [comment]
> […] I'm not interested in anything other than the fluent repo for fluent-bit and would prefer the single line view if possible […]

We do have the same problem as in #37. There is no reference to the repository from where the chart has been installed.

**Comment by stevehipwell** [comment]
I agree that #37 would need to be implemented to do anything more about this, and it would only help if there was a single "match".

Your example above is a common one and the MVP solution for #37 would give you a single "match" and thus single line output. 

> There is no reference to the repository from where the chart has been installed.

I feel that this is an issue with Helm, I'd like to see the source (actual remote repo url or file constant) and checksum stored in the Helm version secret. This would solve our problem here and it would also allow simple Helm auditing.

**Comment by l0nax** [comment]
I think this has been fixed. Can we close it @stevehipwell?

**Comment by stevehipwell** [comment]
I think so, I'll test in the morning but happy for you to close first.

**Comment by stevehipwell** [comment]
@l0nax I get the following errors during the upgrade.

Before:
```
/home/hipwells/.local/share/helm/plugins/helm-whatup/install-binary.sh: 13: /home/hipwells/.local/share/helm/plugins/helm-whatup/install-binary.sh: [[: not found
```

After:
```
/home/hipwells/.local/share/helm/plugins/helm-whatup/install-binary.sh: 93: /home/hipwells/.local/share/helm/plugins/helm-whatup/install-binary.sh: [[: not found
```

**Comment by l0nax** [comment]
I think I know why this is happening

**Comment by l0nax** [comment]
@stayleen what do you mean with _After_ and _Before_?

**Comment by l0nax** [comment]
@stevehipwell What version of `whatup` do you have installed?

**Comment by stevehipwell** [comment]
@l0nax before and after the download output. I was on `v0.4.3` and upgraded to `v0.5.0`.

```
Plugin version.............: v0.5.0
helm.sh/helm/v3 pkg version: v3.5.0
```

**Comment by l0nax** [comment]
But version v0.5.0 is now installed?

**Comment by stevehipwell** [comment]
@l0nax it is installed but the output seems to be incorrect, specifically around my _fluent-bit_ example from above. Stable is deprecated but is showing here as not, aws is missing, my installed version is 1.6.10 and stable is highlighted green not fluent.

```
NAME                       fluent-bit
NAMESPACE                  logging
INSTALLED CHART VERSION    0.8.2
INSTALLED APP VERSION      1.3.7

REPOSITORY      DEPRECATED      CHART VERSION   APP VERSION     UPDATED
stable          false           2.10.2          1.3.7           2020-11-09 22:27:18.348653586 +0000 UTC
fluent          false           0.10.0          1.6.10          2021-01-28 01:26:10.588408252 +0000 UTC
grafana         false           2.2.0           v2.1.0          2020-12-24 15:07:11.404389629 +0000 UTC
```

**Comment by l0nax** [comment]
@stevehipwell The `stable` bug has been fixed with 2fade326a0cd75df5406b0b415437c1242a67af3 (check out the commit summary if you want to understand the bug).

> […] stable is highlighted green not fluent.

Can you please take a screenshot?

**Comment by stevehipwell** [comment]
@l0nax screenshot as requested.

![image](https://user-images.githubusercontent.com/6552347/106140153-4bba6f80-6166-11eb-82cb-707101c6e2ed.png)

**Comment by l0nax** [comment]
@stevehipwell Can you please install the _development_ version, re-run `whatup` and post the Screenshot?

**Comment by stevehipwell** [comment]
@l0nax is there a development binary or do I need to build from source?

**Comment by l0nax** [comment]
I'm sorry. I had to eat something.

You can compile the development version as described in the [README.md](https://github.com/fabmation-gmbh/helm-whatup#developer-from-source-install).

Or I can upload the compiled version for you if you want.

**Comment by stevehipwell** [comment]
@l0nax either way would work, if you upload a version I'll be able to test pretty much immediately otherwise I'll probably need to wait until I have time to setup a build.

**Comment by l0nax** [comment]
[helm-whatup-0.5.1-beta-linux-amd64.tar.gz](https://github.com/fabmation-gmbh/helm-whatup/files/5887454/helm-whatup-0.5.1-beta-linux-amd64.tar.gz)
[helm-whatup-0.5.1-beta-darwin-amd64.tar.gz](https://github.com/fabmation-gmbh/helm-whatup/files/5887457/helm-whatup-0.5.1-beta-darwin-amd64.tar.gz)

**Comment by stevehipwell** [comment]
@l0nax I'm getting the following error, I had to remove the plugin before I could get this far.

```
➜  ~ SKIP_BIN_INSTALL=1 helm plugin install /tmp/helm-whatup
sh: 1: /home/hipwells/.local/share/helm/plugins/helm-whatup/install-binary.sh: not found
Error: plugin install hook for "whatup" exited with error
```

**Comment by l0nax** [comment]
I know this is a dumb question but is `/bin/sh` working for you?

**Comment by stevehipwell** [comment]
@l0nax yes it. I've added the `ls` output for the extracted tar. I don't see an install script?

```
➜  ~ ls /home/hipwells/.local/share/helm/plugins/helm-whatup
bin  LICENSE.md  plugin.yaml  README.md
➜  ~ ls /home/hipwells/.local/share/helm/plugins/helm-whatup/bin
helm-whatup
```

**Comment by l0nax** [comment]
Wait a moment.

Did you compile the application on your own or did you use the binaries provided with https://github.com/fabmation-gmbh/helm-whatup/issues/36#issuecomment-769053674?

**Comment by stevehipwell** [comment]
Binaries provided after extracting the tar, but I could have done this wrong

```
SKIP_BIN_INSTALL=1 helm plugin install /tmp/helm-whatup
```

**Comment by l0nax** [comment]
`helm install` will not work – since the `install-binary.sh` script is not packed with the tar archives.
You have to manually copy the binary to `$HOME/.local/share/helm/plugins`

Or just add the `install-binary.sh` script to `/tmp/helm-whatup`

**Comment by stevehipwell** [comment]
Thanks @l0nax I've put a screenshot of the dev output (it is reporting at v0.5.0) which looks the same.

![image](https://user-images.githubusercontent.com/6552347/106163372-fe97c700-6180-11eb-9ccd-bd0b12d18fd7.png)

**Comment by l0nax** [comment]
@stevehipwell The version should be `v0.5.1-beta`. Would it be possible for you to install the plugin from sources?

**Comment by l0nax** [comment]
Because of #38 i've released [v0.5.1](https://github.com/fabmation-gmbh/helm-whatup/releases/tag/v0.5.1).

So you can simply update the plugin.

**Comment by stevehipwell** [comment]
@l0nax I've installed `v0.5.1` and I'm seeing a number of issues, but it looks like it's down to the repo detection.

- Non-deterministic current repo highlighting (two concurrent runs show's different output)
- Incorrect current app version (both in single line and multi-repo view)
- Incorrect upgrade repo (miss match of app version, chart version and repo)

The following image shows the first two issues.
![image](https://user-images.githubusercontent.com/6552347/106433821-98ed5880-6468-11eb-829e-f9d4cd38d2f7.png)

**Comment by l0nax** [comment]
> Incorrect current app version (both in single line and multi-repo view)
 
Fixed with f57902464f8e05800183d49d27d8c8dc58f7ad29

> Non-deterministic current repo highlighting (two concurrent runs show's different output)

This is the problem I described in https://github.com/fabmation-gmbh/helm-whatup/issues/37#issuecomment-768279818.
If two repositories share the _same_ chart version for the _same_ app version, we cannot find the _real_ chart repository from where the Chart has been installed from.

> Incorrect upgrade repo (miss match of app version, chart version and repo)

What do you exactly mean by that?



Version _v0.5.2_ has been released since the output is not usable if it does not show the correct information.

**Comment by stevehipwell** [comment]
> Incorrect current app version (both in single line and multi-repo view)

This appears to have been fixed with `v0.5.2`.

> Non-deterministic current repo highlighting (two concurrent runs show's different output)

These chart's don't share the same sets of app and chart versions but the highlighting is still incorrect on some runs. The repo order is also non-deterministic, it's not always the highlighted repo on top, nor is it alphabetic order.

> Incorrect upgrade repo (miss match of app version, chart version and repo)

I have a chart installed that has it's official repo (low versions) and a deprecated set of charts in another repo (high versions); the update is showing on a single line and is reporting the last chart version pre-deprecation from the deprecated repo. On top of this chart being deprecated this change would downgrade the app (from `0.20.0` to `0.9.0`).

**Comment by l0nax** [comment]
@stevehipwell Which chart and app version do you have installed for your `fluent-bit` deployment?

**Comment by stevehipwell** [comment]
@l0nax I have chart `fluent-bit-0.8.2` installed which has an app version of `1.6.10` and is installed from https://fluent.github.io/helm-charts/.

The chart causing the third issue is `descheduler-0.20.0` with app version `0.20.0` installed from https://kubernetes-sigs.github.io/descheduler/. The deprecated _descheduler_ chart in https://stevehipwell.github.io/helm-charts/ is being given as the upgrade.

**Comment by l0nax** [comment]
I've improved the source repository search function in ec5bc6031942df8d3ed1ac925a034a406eb298da.

> The chart causing the third issue is descheduler-0.20.0 with app version 0.20.0 installed from https://kubernetes-sigs.github.io/descheduler/. The deprecated descheduler chart in https://stevehipwell.github.io/helm-charts/ is being given as the upgrade.


Can you post a screenshot of the `helm whatup` output, please?

**Comment by stevehipwell** [comment]
![image](https://user-images.githubusercontent.com/6552347/106444009-1dde6f00-6475-11eb-8682-9553b3bdb2db.png)

**Comment by l0nax** [comment]
@stevehipwell With version _v0.5.3_ all those bugs should be fixed. I'm sorry for the inconvenience.

**Comment by stevehipwell** [comment]
@l0nax there is no need to apologise, I appreciate all the work you've done with this plugin.

Unfortunately I'm still seeing issues with my output.

![image](https://user-images.githubusercontent.com/6552347/106585862-b4776280-653f-11eb-9bab-c78e4c2f7e85.png)

- The `deschduler` chart isn't from the `stevehipwell` repo, these repos don't have overlapping versions
- The `fluent-bit` chart isn't from the `grafana` repo, these repos don't have overlapping versions
- The `metrics-server` isn't from the `bitnami` repo, these repos don't have overlapping versions

**Comment by stevehipwell** [comment]
Possibly worth pointing out that `metrics-server` is the deprecated chart from the old `stable` repo.

**Comment by l0nax** [comment]
> Possibly worth pointing out that `metrics-server` is the deprecated chart from the old `stable` repo.

I think we should add a flag to enable/disable suggestions for a new repo.

**Or** we should, at least, inform the user that the chart from the source repository is marked as _deprecated_.

**Comment by stevehipwell** [comment]
I'd vote for flagging as deprecated and showing the multi line output.

**Comment by l0nax** [comment]
To support this, I have to rewrite big parts of the plugin. And it may break some tools that use, i.e., the JSON output.

**Comment by stevehipwell** [comment]
@l0nax what about solving the bug with the `fluent-bit` and `descheduler` charts first? I can live with the current behaviour for deprecated charts like `metrics-server`.

**Comment by l0nax** [comment]
I will solve it, one moment please.

**Comment by l0nax** [comment]
@stevehipwell, will you be able to install the plugin from sources? Because I want first to make sure that this works before making a new release.

**Comment by stevehipwell** [comment]
@l0nax I should be able to.

**Comment by l0nax** [comment]
@stevehipwell I've pushed the fix to `develop`. Can you please test it?

**Comment by stevehipwell** [comment]
@l0nax that looks to have fixed it.

![image](https://user-images.githubusercontent.com/6552347/106599302-cad9ea00-6550-11eb-994b-c8bb21817965.png)

**Comment by l0nax** [comment]
With [v0.5.4](https://github.com/fabmation-gmbh/helm-whatup/releases/tag/v0.5.4) the fixes have been released.

**Comment by stevehipwell** [comment]
Thanks @l0nax. There is still one outstanding query, my GitLab chart (https://charts.gitlab.io/) is showing up as deprecated but it isn't.

![image](https://user-images.githubusercontent.com/6552347/106635947-536c8080-6579-11eb-87fa-69283c14c1bb.png)

**Comment by l0nax** [comment]
@stevehipwell What chart version do you have installed? Because `hem whatup` does not print this message for our gitlab deployment.

**Comment by stevehipwell** [comment]
@l0nax `gitlab-4.8.1` which is one off the latest (`gitlab-4.8.2`).

**Comment by l0nax** [comment]
Can you paste the output of `helm --debug whatup` please?

**Comment by stevehipwell** [comment]
```
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.3.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.9.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.9.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.4.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.4.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.5.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.2.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.2.9 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.2.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.8.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.3.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.1.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.1.8 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.1.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 0.2.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.5.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.2.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.1.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.4.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.4.9 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.6.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.7.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.6.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.3.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.7.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.1.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.5.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.3.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.3.13 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.1.13 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 0.2.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.3.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.0.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.0.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.5.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.3.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.6.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.3.8 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.7.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.3.7 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.6.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.0.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.1.8 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.5.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.2.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.3.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.2.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.1.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.1.9 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.3.8 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.2.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.3.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.2.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.3.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.3.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.5.8 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.0.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.5.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.0.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.2.10 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.6.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.1.11 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.6.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.1.7 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.0.7 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.2.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.9.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.1.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.7.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.9.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.6.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.4.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.5.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.3.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.5.7 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.1.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.5.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.7.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.2.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.6.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.7.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.4.10 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.5.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.2.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.0.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.7.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.1.9 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.1.10 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.4.8 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.7.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.1.14 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.4.12 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.2.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.8.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.1.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.4.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.6.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.0.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.3.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.3.7 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.6.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.2.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.2.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.3.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.6.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.4.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.2.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.2.12 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.0.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.1.11 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.3.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.0.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.2.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.5.7 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.4.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.1.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.3.9 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.3.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.5.9 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.0.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.3.12 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.4.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.1.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.1.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.2.7 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.8.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.6.8 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.6.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.3.8 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.0.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.0.12 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.1.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.4.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.5.11 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.4.11 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.7.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.2.7 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.3.10 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.5.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.2.8 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.0.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.2.8 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.7.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.4.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.2.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.8.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.6.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.3.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.1.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.4.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.1.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.4.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.5.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.2.11 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.4.7 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.2.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.6.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.5.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.7.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.9.8 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.4.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.0.10 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.9.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.3.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.3.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.1.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.3.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 0.3.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.6.9 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 0.3.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.3.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.0.7 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.9.7 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.0.9 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.6.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.1.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.3.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.2.8 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.4.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.1.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 0.2.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.0.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.5.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.0.7 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.9.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.4.13 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.1.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.0.8 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.1.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.2.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.2.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.0.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.2.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.3.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.1.10 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.7.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.3.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.0.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.5.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.4.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.2.10 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.3.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.2.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.1.12 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.3.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.2.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.1.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.2.7 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.2.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 0.3.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.2.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.4.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.1.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.4.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.3.7 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 0.2.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.2.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.0.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 0.3.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.0.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.1.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.4.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.0.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.4.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.3.12 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.7.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.8.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.0.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.6.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.5.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.5.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.5.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.1.8 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.1.7 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.1.12 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.0.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 0.3.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 0.3.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.8.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Found newer version 'gitlab/gitlab' 4.8.2 > 4.8.2
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.0.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.2.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 0.2.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.1.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.3.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.8.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.1.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.3.10 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.3.11 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.2.5 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.2.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.2.9 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.3.9 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.8.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.0.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.1.7 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 3.1.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.8.0 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.9.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.1.4 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.8.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.0.2 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.6.7 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.5.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 1.1.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.0.1 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.5.10 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 2.6.3 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.6.6 [constrain: '> 4.8.1']
2021/02/03 10:05:25 [debug] Comparing version of original chart 'gitlab' => 4.8.1 with version (gitlab/gitlab) 4.0.11 [constrain: '> 4.8.1']
WARNING: The newest version for the chart 'gitlab/gitlab' is marked as DEPRECATED!
```

**Comment by l0nax** [comment]
The reason for this behavior is because version `0.1.9` has been marked as `deprecated`.

I will fix this, but I thought that if someone does mark a chart as _deprecated_, no one will use the chart anymore, and the author shouldn't revert this decision.

**Comment by stevehipwell** [comment]
@l0nax I agree that would have been my expected logic but it appears that some charts authors have a different idea. Do they only have the one version deprecated?

**Comment by l0nax** [comment]
Yes, only version `0.1.9` has been marked deprecated.

**Comment by stevehipwell** [comment]
I've just looked up the Helm docs and it looks like we're [mistaken](https://helm.sh/docs/topics/charts/#deprecating-charts).

> The chart name can be later reused by publishing a newer version that is not marked as deprecated.

**Comment by l0nax** [comment]
Oh, that's interesting.

**Comment by l0nax** [comment]
@stevehipwell, can you please test the latest development version?

**Comment by stevehipwell** [comment]
Thanks @l0nax the development version is working correctly.

**Comment by stevehipwell** [comment]
@l0nax when do you think you will be releasing this?

**Comment by l0nax** [comment]
@stevehipwell Released.

I'm going to close this issue now. Feel free to reopen it or create a new one. :+1:

**Comment by stevehipwell** [comment]
Thanks @l0nax!
